languageCode = "en"
languageName = "English"
weight = 1

title = "Matsunaga Lab"
copyright = "Yasuhiro Matsunaga"

[params]
  dateFormat = "Jan 2, 2006"
  mainSections = ["post"]
  description = "Computational Biophysics @ Saitama University"

[params.author]
  name = "Matsunaga Lab"
  image = "img/mats04.png"
  headline = "Computational Biophysics"
  bio = "We study molecular simulations and data science to understand and control life phenomena."
  links = [
    { github = "https://github.com/matsunagalab" },
    { youtube = "https://www.youtube.com/channel/UCO3SW9xZ5DoPOcvdPX7DaFg/videos" },
    { x-twitter = "https://x.com/ymatsunagalab" },
  ]
